setwd("c:\\data")
rm(list=ls())


url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_ags.txt")
ags<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_bc.txt")
bc<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_bcs.txt")
bcs<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_camp.txt")
cam<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_coah.txt")
coa<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_col.txt")
col<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_chis.txt")
chis<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_chih.txt")
chih<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_df.txt")
df<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_dgo.txt")
dgo<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_gto.txt")
gto<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_gro.txt")
gro<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_hgo.txt")
hgo<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_jal.txt")
jal<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_mex.txt")
mex<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_mich.txt")
mich<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_mor.txt")
mor<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_nay.txt")
nay<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_nl.txt")
nl<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_oax.txt")
oax<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_pue.txt")
pue<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_qro.txt")
qro<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_qroo.txt")
qroo<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_slp.txt")
slp<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_sin.txt")
sin<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_son.txt")
son<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_tab.txt")
tamps<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_tamps.txt")
tab<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_tlax.txt")
tlax<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_ver.txt")
ver<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_yuc.txt")
yuc<-readLines(url)
url<-("http://www.ife.org.mx/documentos/Estadisticas2006/presidente/txts/presidente_zac.txt")
zac<-readLines(url)


tmp1<-c("emmedo=ags",ags,"emmedo=bc",bc,"emmedo=bcs",bcs,"emmedo=cam",cam,"emmedo=chis",coa,"emmedo=chih",col)
tmp2<-c("emmedo=col",chis,"emmedo=coa",chih,"emmedo=df",df,"emmedo=dgo",dgo,"emmedo=gro",gto,"emmedo=gto",gro)
tmp3<-c("emmedo=hgo",hgo,"emmedo=jal",jal,"emmedo=mex",mex,"emmedo=mich",mich,"emmedo=mor",mor,"emmedo=nay",nay)
tmp4<-c("emmedo=nl",nl,"emmedo=oax",oax,"emmedo=pue",pue,"emmedo=qro",qro,"emmedo=qroo",qroo,"emmedo=sin",slp)
tmp5<-c("emmedo=slp",sin,"emmedo=son",son,"emmedo=tab",tamps,"emmedo=tamps",tab,"emmedo=tlax",tlax)
tmp6<-c("emmedo=ver",ver,"emmedo=yuc",yuc,"emmedo=zac",zac)
all<-c(tmp1,tmp2,tmp3,tmp4,tmp5,tmp6)

write.table(all, "c:/data/orrvotes/res.txt", sep="\t")

xx
ags
bc
bcs
cam
coa
col
chis
chih
df
dgo
gto
gro
hgo
jal
mex
mich
mor
nay
nl
oax
pue
qro
qroo
slp
sin
son
tamps
tab
tlax
ver
yuc
zac



